
---
# Multiple projects are expected, so we specify the "base directory" (e.g. "/workspace")
workspaceLocation: "."
# Custom Docker Image
image: ghcr.io/cicd-lectures/gitpod:latest
  ## Uncomment to build image from source
  #file: .gitpod.Dockerfile
tasks:
  - name: Use "main" as default branch for new git repositories
    before: git config --global init.defaultBranch main
vscode:
  extensions:
    - redhat.java
    - shellcheck
    - Pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack
...
